### ISSUE TITLE
请求具体股票或者其他标的数据报错： HTTPSConnectionPool(host='searchapi.eastmoney.com', port=443): Max retries exceeded 

### ISSUE THREAD

**Issue by Crown-Messi** [tkfy920/qstock#31]
Traceback (most recent call last):
  File ".\processData.py", line 19, in <module>
    df=qs.realtime_data(code="603266.SH")
  File "D:\programs\miniconda3\envs\QuantTrade\lib\site-packages\qstock\data\trade.py", line 232, in realtime_data
    return stock_realtime(code)
  File "D:\programs\miniconda3\envs\QuantTrade\lib\site-packages\qstock\data\trade.py", line 180, in stock_realtime
    secids = [get_code_id(code)
  File "D:\programs\miniconda3\envs\QuantTrade\lib\site-packages\qstock\data\trade.py", line 180, in <listcomp>
    secids = [get_code_id(code)
  File "D:\programs\miniconda3\envs\QuantTrade\lib\site-packages\qstock\data\util.py", line 493, in get_code_id
    response = session.get(url, params=params).json()
  File "D:\programs\miniconda3\envs\QuantTrade\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\programs\miniconda3\envs\QuantTrade\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\programs\miniconda3\envs\QuantTrade\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\programs\miniconda3\envs\QuantTrade\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='searchapi.eastmoney.com', port=443): Max retries exceeded with url: /api/suggest/get?input=603266.SH&type=14&token=D43BF722C8E33BDC906FB84D85E326E8 (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))))

**Comment by Crown-Messi** [comment]
已解决，需要降低urllib版本
pip install urllib3==1.25.11
