### ISSUE TITLE
编译总是提示没有 mini_racer.dll

### ISSUE THREAD

**Issue by zephorxi** [tkfy920/qstock#6]
编译总是提示没有 mini_racer.dll，好像是py_mini_racer的问题，机子里没有这个dll，找不到解决方法。
File "D:\Python310-32\lib\site-packages\py_mini_racer-0.6.0-py3.10.egg\py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
    raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH))
RuntimeError: Native library not available at D:\Python310-32\lib\site-packages\py_mini_racer-0.6.0-py3.10.egg\py_mini_racer\mini_racer.dll
Exception ignored in: <function MiniRacer.__del__ at 0x03140610>
Traceback (most recent call last):
  File "D:\Python310-32\lib\site-packages\py_mini_racer-0.6.0-py3.10.egg\py_mini_racer\py_mini_racer.py", line 315, in __del__
    self.ext.mr_free_context(getattr(self, "ctx", None))
AttributeError: 'NoneType' object has no attribute 'mr_free_context'

**Comment by tkfy920** [comment]
重新安装下py_mini_racer
